name: xai_compress_authenticator
description: XAICD mobile authenticator with TOTP, QR enrollment, secure storage and biometric lock.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  otp: ^3.1.4
  flutter_secure_storage: ^11.0.0
  local_auth: ^3.0.2
  http: ^1.4.0
  provider: ^6.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
