import Link from 'next/link';import {Smartphone,Monitor,Terminal,CheckCircle2,Clock3} from 'lucide-react';import {SectionHeading} from '@/components/section-heading';import manifest from '@/lib/releases.json';import {productionReleases} from '@/lib/releases.mjs';
export const metadata={title:'Downloads',description:'XAI-Compress Mobile, Desktop and CLI availability and verified release downloads.'};
const releases=productionReleases(manifest);
function release(platform:string){return releases.find(r=>r.platform===platform)}
function Availability({platform}:{platform:string}){const item=release(platform);return item?<a className="button" href={item.url}>Download {item.filename}</a>:<span className="availability"><Clock3 size={16}/>No verified public release</span>}
export default function Downloads(){return <><section className="page-hero downloads-hero"><div className="container"><SectionHeading eyebrow="Product clients" title="XAI-Compress, wherever you work" body="Choose mobile, desktop or command line. Download buttons appear only for reviewed, signed and installation-tested releases in the release manifest."/><div className="product-downloads">
 <article><div className="product-icon"><Smartphone/></div><span>Mobile</span><h2>XAI Mobile & Authenticator</h2><p>The Flutter mobile application implements local TOTP account enrollment and offline code generation. Store distribution is not yet verified.</p><div className="platform-row"><div><b>Android</b><small>Source-build and test distribution only</small><Availability platform="android"/></div><div><b>iOS</b><small>No verified artifact or store release</small><Availability platform="ios"/></div></div></article>
 <article><div className="product-icon"><Monitor/></div><span>Desktop</span><h2>XAI-Compress Desktop</h2><p>The Flutter desktop client provides account access and file workflows. A Windows test build exists in workspace validation output, but it is unsigned and not a public release.</p><div className="platform-row three"><div><b>Windows</b><small>Unsigned test build only</small><Availability platform="windows"/></div><div><b>Linux</b><small>No verified artifact</small><Availability platform="linux"/></div><div><b>macOS</b><small>No verified artifact</small><Availability platform="macos"/></div></div></article>
 <article className="cli-card"><div className="product-icon"><Terminal/></div><span>Command line</span><h2>XAI-Compress CLI</h2><p>The Python package exposes compression, decompression and inspection workflows for local use.</p><pre><code><i>$</i> xai-compress compress &lt;file&gt;{`\n`}<i>$</i> xai-compress decompress &lt;file.xaic&gt;</code></pre><div className="platform-notes"><span><CheckCircle2 size={16}/>Python package source present</span><span>Version 0.1.0</span><span>Windows, Linux and macOS with compatible Python dependencies</span></div><Availability platform="cli"/><Link className="text-link" href="/docs">Read CLI documentation →</Link></article>
 </div></div></section></>}
