Foreground yes
User clamav
DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 127.0.0.1
MaxThreads 2
ReadTimeout 120
CommandReadTimeout 30
SendBufTimeout 120
MaxScanTime 120000
MaxScanSize 1G
MaxFileSize 1G
StreamMaxLength 1G
AlertExceedsMax yes
LogTime yes
LogClean no
LogSyslog no
LogFile /dev/stdout
LogFileUnlock yes
PidFile /run/clamav/clamd.pid
