import {beforeEach,describe,expect,it,vi} from 'vitest';
import {of,throwError} from 'rxjs';
import {LoginPage} from '../src/app/pages/login.page';
import {RegisterPage} from '../src/app/pages/register.page';
import {VerifyAccountPage} from '../src/app/pages/verify-account.page';
import {ForgotPasswordPage} from '../src/app/pages/forgot-password.page';
import {SecurityPage} from '../src/app/pages/security.page';
import {AuthService} from '../src/app/core/auth.service';
import {ApiService} from '../src/app/core/api.service';
import {routes} from '../src/app/app.routes';
import {ShellComponent} from '../src/app/layout/shell.component';
import {DashboardPage} from '../src/app/pages/dashboard.page';
import {SharesPage} from '../src/app/pages/shares.page';

const flush=()=>new Promise(resolve=>setTimeout(resolve,0));
beforeEach(()=>{localStorage.clear();sessionStorage.clear()});

describe('staged login',()=>{
 const setup=(login=vi.fn().mockResolvedValue({mfa_enabled:false}),verifyMfa=vi.fn().mockResolvedValue({mfa_enabled:true}))=>{const router={navigateByUrl:vi.fn().mockResolvedValue(true)};const auth={login,verifyMfa,hasMfaChallenge:()=>true,cancelMfa:vi.fn()};return {login,verifyMfa,router,page:new LoginPage(auth as never,router as never)}};
 it('requires authenticator setup before an unenrolled account can use the workspace',async()=>{const {page,login,router}=setup();page.email='person@example.com';page.password='correct-password';await page.submitCredentials();expect(login).toHaveBeenCalledWith(page.email,'correct-password');expect(page.step()).toBe('credentials');expect(router.navigateByUrl).toHaveBeenCalledWith('/security')});
 it('moves to code verification only when valid credentials require MFA',async()=>{const error={status:401,error:{detail:'Valid TOTP code required'}};const {page}=setup(vi.fn().mockRejectedValue(error));page.email='person@example.com';page.password='correct-password';await page.submitCredentials();expect(page.step()).toBe('mfa');expect(page.error()).toBe('')});
 it('handles an invalid TOTP without exposing backend details',async()=>{const login=vi.fn().mockRejectedValue({status:401,error:{detail:'Valid TOTP code required'}});const verifyMfa=vi.fn().mockRejectedValue({status:401,error:{detail:'internal detail'}});const {page}=setup(login,verifyMfa);page.email='person@example.com';page.password='correct-password';await page.submitCredentials();page.totp='123456';await page.verifyCode();expect(page.step()).toBe('mfa');expect(page.error()).toContain('Invalid verification code');expect(page.error()).not.toContain('internal')});
 it('opens the dashboard only after the backend accepts the mobile code',async()=>{const login=vi.fn().mockRejectedValue({status:401,error:{detail:'Valid TOTP code required'}});const {page,router,verifyMfa}=setup(login);page.email='person@example.com';page.password='correct-password';await page.submitCredentials();page.totp='654321';await page.verifyCode();expect(verifyMfa).toHaveBeenCalledWith('654321');expect(router.navigateByUrl).toHaveBeenCalledWith('/dashboard')});
});

describe('registration',()=>{
 const setup=()=>{const auth={register:vi.fn().mockResolvedValue({verification_required:true})};const router={navigate:vi.fn().mockResolvedValue(true),navigateByUrl:vi.fn().mockResolvedValue(true)};return {auth,router,page:new RegisterPage(auth as never,router as never)}};
 it('validates profile fields, backend password bounds, and matching confirmation',async()=>{const {page,auth}=setup();page.fullName='Test Person';page.phone='+33612345678';page.email='bad';page.password='short';page.confirmPassword='different';await page.submit();expect(page.validation()).toContain('valid email');expect(auth.register).not.toHaveBeenCalled();page.email='person@example.com';await page.submit();expect(page.validation()).toContain('10 characters');page.password='correct-password';page.confirmPassword='other-password';await page.submit();expect(page.validation()).toContain('do not match')});
 it('registers a pending account and continues to verification',async()=>{const {page,auth,router}=setup();page.fullName='Test Person';page.phone='+33612345678';page.email='person@example.com';page.password=page.confirmPassword='correct-password';await page.submit();expect(auth.register).toHaveBeenCalledWith(page.fullName,page.email,page.phone,page.password);expect(router.navigate).toHaveBeenCalledWith(['/verify-account'],{state:{email:page.email}})});
});

describe('email account verification',()=>{
 const setup=(post=vi.fn(()=>of({verified:true})))=>{const router={navigateByUrl:vi.fn().mockResolvedValue(true)};const page=new VerifyAccountPage({post} as never,router as never);page.email='person@example.com';return {page,post,router}};
 it('submits the six-digit code in a POST body and routes successful verification to login',async()=>{vi.useFakeTimers();const {page,post,router}=setup();page.code='123456';const pending=page.verify();await vi.runAllTimersAsync();await pending;expect(post.mock.calls[0][0]).toContain('/auth/verification/email/confirm');expect(post.mock.calls[0][0]).not.toContain('123456');expect(post.mock.calls[0][1]).toEqual({identifier:'person@example.com',code:'123456'});expect(page.success()).toBe(true);expect(router.navigateByUrl).toHaveBeenCalledWith('/login');vi.useRealTimers()});
 it('resends with loading-safe state, visible cooldown, and sanitized failure',async()=>{const {page,post}=setup();await page.resend();expect(post.mock.calls[0][0]).toContain('/auth/verification/email/send');expect(page.cooldown()).toBe(60);page.ngOnDestroy();post.mockImplementation(()=>throwError(()=>({error:{detail:'private provider detail'}})));page.cooldown.set(0);await page.resend();expect(page.message()).toContain('cannot be sent');expect(page.message()).not.toContain('private')});
 it('rejects malformed codes locally',async()=>{const {page,post}=setup();page.code='12x';page.digitsOnly();await page.verify();expect(page.code).toBe('12');expect(post).not.toHaveBeenCalled()});
});

describe('forgot-password recovery',()=>{
 const setup=()=>{const post=vi.fn((url:string)=>url.endsWith('/verify-code')?of({reset_token:'short-lived-reset-authorization'}):of({accepted:true}));return {post,page:new ForgotPasswordPage({post} as never)}};
 it('uses POST bodies for forgot, code verification, and password reset without URL secrets',async()=>{const {page,post}=setup();page.identifier='person@example.com';await page.send();expect(page.step()).toBe(2);page.code='654321';await page.verify();expect(page.step()).toBe(3);page.password=page.confirm='new-correct-password';await page.reset();expect(page.step()).toBe(4);expect(post.mock.calls.map(call=>call[0])).toEqual(expect.arrayContaining([expect.stringContaining('/auth/password/forgot'),expect.stringContaining('/auth/password/verify-code'),expect.stringContaining('/auth/password/reset')]));expect(post.mock.calls.every(call=>!call[0].includes('654321')&&!call[0].includes('short-lived-reset'))).toBe(true);expect(localStorage.length).toBe(0);expect(sessionStorage.length).toBe(0)});
 it('keeps generic sanitized errors and does not advance',async()=>{const post=vi.fn(()=>throwError(()=>({error:{detail:'private provider response'}})));const page=new ForgotPasswordPage({post} as never);page.identifier='person@example.com';await page.send();expect(page.step()).toBe(1);expect(page.message()).toContain('could not be completed');expect(page.message()).not.toContain('private')});
 it('exposes both recovery and login routes',()=>{expect(routes.map(route=>route.path)).toEqual(expect.arrayContaining(['forgot-password','login']))});
});

describe('current authenticator enrollment',()=>{
 const setup=async(overrides:Record<string,unknown>={})=>{const api={me:vi.fn(()=>of({email:'person@example.com',phone_number:'+33612345678',email_verified:true,phone_verified:false})),totpStatus:vi.fn(()=>of({state:'not_configured',enrollment_id:null})),startAuthenticator:vi.fn(()=>of({enrollment_id:'a'.repeat(32),expires_in_seconds:1200})),confirmAuthenticator:vi.fn(()=>of({enabled:true,mfa_enabled:true,access_token:'full',refresh_token:'refresh'})),authDevices:vi.fn(()=>of([])),revokeDevice:vi.fn(()=>of({status:'revoked'})),recoveryCodes:vi.fn(()=>of({codes:['recovery-one'],shown_once:true})),...overrides};const auth={completeEnrollment:vi.fn()};const router={navigateByUrl:vi.fn().mockResolvedValue(true)};const page=new SecurityPage(api as unknown as ApiService,auth as never,router as never);await flush();return {api,auth,router,page}};
 it('shows pending setup without a QR or raw secret',async()=>{const {page}=await setup();expect(page.state()).toBe('pending_activation');expect(page.statusLabel()).toBe('Pending');expect(page.enrollmentId).toBe('a'.repeat(32));expect(localStorage.length).toBe(0)});
 it('starts enrollment without returning secret material to the web app',async()=>{const {page,api}=await setup();await page.start();expect(api.startAuthenticator).toHaveBeenCalledTimes(2);expect(page.state()).toBe('pending_activation');expect(page.enrollmentId).toBe('a'.repeat(32))});
 it('verifies the mobile TOTP before activating MFA',async()=>{const {page,api,auth,router}=await setup();page.code='123456';await page.confirm();expect(api.confirmAuthenticator).toHaveBeenCalledWith('a'.repeat(32),'123456');expect(auth.completeEnrollment).toHaveBeenCalledOnce();expect(page.state()).toBe('enabled');expect(router.navigateByUrl).toHaveBeenCalledWith('/dashboard')});
 it('does not activate when enrollment confirmation fails',async()=>{const {page}=await setup({confirmAuthenticator:vi.fn(()=>throwError(()=>({status:400,error:{detail:'secret internal message'}})))});page.code='123456';await page.confirm();expect(page.state()).toBe('pending_activation');expect(page.message()).toContain('Invalid verification code');expect(page.message()).not.toContain('internal')});
 it('clears transient enrollment state on navigation',async()=>{const {page}=await setup();page.code='123456';page.ngOnDestroy();expect(page.code).toBe('');expect(page.enrollmentId).toBe('')});
 it('lists and revokes only through the authenticated device API',async()=>{const device={device_id:'device_abcdefghijklmnop',platform:'android',app_version:'1.0',status:'active',registered_at:'2026-01-01',last_activity:'2026-01-02'};const {page,api}=await setup({authDevices:vi.fn(()=>of([device]))});await page.loadDevices();expect(page.devices()).toEqual([device]);await page.revokeDevice(device.device_id);expect(api.revokeDevice).toHaveBeenCalledWith(device.device_id)});
});

describe('secure sharing workspace',()=>{
 it('loads owned files and share history',async()=>{const api={files:vi.fn(()=>of([{id:1,name:'owned.bin',status:'completed'}])),shares:vi.fn(()=>of([{id:2,file_name:'owned.bin',recipient_email:'recipient@example.com',expires_at:'2026-01-01',status:'active',download_count:0,max_downloads:1}]))};const page=new SharesPage(api as never);await flush();expect(page.files().length).toBe(1);expect(page.shares().length).toBe(1)});
 it('creates and revokes using backend APIs with truthful email status',async()=>{const api={files:vi.fn(()=>of([{id:7,name:'owned.bin',status:'completed'}])),shares:vi.fn(()=>of([])),share:vi.fn(()=>of({share_code:'SAFE-CODE',expires_at:'2026-01-01',recipient_email:'recipient@example.com',email_delivery:'captured_by_mailpit'})),revokeShare:vi.fn(()=>of({status:'revoked'}))};const page=new SharesPage(api as never);await flush();page.fileId=7;page.email='recipient@example.com';page.expiresMinutes=1440;page.create();await flush();expect(api.share).toHaveBeenCalledWith(7,'recipient@example.com',1440);expect(page.code()).toBe('SAFE-CODE');expect(page.emailStatusLabel(page.createdDelivery())).toContain('Mailpit');page.revoke({id:9} as never);await flush();expect(api.revokeShare).toHaveBeenCalledWith(9)});
 it('redeems metadata and maps protected share states to safe messages',async()=>{const metadata={file:{name:'owned.bin.xaic',size:16},sender:{name:'Test Sender',email:'sender@example.com'},expires_at:'2026-10-01T18:30:00',remaining_downloads:1,max_downloads:1};const api={files:vi.fn(()=>of([])),shares:vi.fn(()=>of([])),redeem:vi.fn(()=>of(metadata))};const page=new SharesPage(api as never);await flush();page.redeemCode='XC-SAFE-CODE';page.redeem();await flush();expect(page.received()).toEqual(metadata);api.redeem.mockReturnValue(throwError(()=>({status:410})));page.redeem();await flush();expect(page.receiveMessage()).toContain('expired');api.redeem.mockReturnValue(throwError(()=>({status:403})));page.redeem();await flush();expect(page.receiveMessage()).toContain('not authorized')});
});

describe('real authentication transport',()=>{
 it('supports logout and relogin with the current mobile code',async()=>{let calls=0;const http={post:vi.fn((url:string,body:Record<string,string|null>)=>{if(url.endsWith('/auth/logout'))return of({logged_out:true});calls++;if(calls===1)return throwError(()=>({status:401,error:{detail:'Valid TOTP code required'}}));expect(body.totp_code).toBe('654321');return of({access_token:'access-fixture',refresh_token:'refresh-fixture'})})};const router={navigateByUrl:vi.fn()};const auth=new AuthService(http as never,router as never);await expect(auth.login('person@example.com','correct-password')).rejects.toBeTruthy();await auth.login('person@example.com','correct-password','654321');expect(auth.authenticated()).toBe(true);auth.logout();expect(auth.authenticated()).toBe(false);expect(localStorage.length).toBe(0)});
 it('places MFA codes in POST bodies and never URLs',()=>{const http={post:vi.fn(()=>of({}))};const api=new ApiService(http as never);api.confirmAuthenticator('a'.repeat(32),'123456');const [url,body]=http.post.mock.calls[0] as unknown as [string,{code:string}];expect(url).not.toContain('123456');expect(body.code).toBe('123456')});
});

describe('authenticated workspace navigation',()=>{
 it('exposes dashboard, compression, restoration, history, security and account routes',()=>{const shell=routes.find(x=>x.path==='');const paths=shell?.children?.map(x=>x.path);expect(paths).toEqual(expect.arrayContaining(['dashboard','compress','inbox','files','security','settings']))});
 it('uses a responsive drawer and real account identity in the shell',()=>{const auth={logout:vi.fn()};const api={me:vi.fn(()=>of({email:'person@example.com',display_name:'Test Person',is_admin:false}))};const shell=new ShellComponent(auth as never,api as never);expect(shell.initials()).toBe('TP');shell.drawer.set(true);shell.close();expect(shell.drawer()).toBe(false)});
 it('derives dashboard totals from real file records',async()=>{const files=[{id:1,name:'one.bin',status:'completed',codec:'static',created_at:'2026-01-01',original_size:10,compressed_size:8},{id:2,name:'two.bin',status:'failed',codec:'static',created_at:'2026-01-02',original_size:10,compressed_size:0}];const api={me:vi.fn(()=>of({display_name:'Test Person'})),files:vi.fn(()=>of(files))};const page=new DashboardPage(api as never);await flush();expect(page.completed()).toBe(1);expect(page.failed()).toBe(1);expect(page.firstName()).toBe('Test')});
});
