-- Additive authenticator/device foundation. Safe to run again.
CREATE TABLE IF NOT EXISTS authenticator_devices (id SERIAL PRIMARY KEY, device_id VARCHAR(64) NOT NULL UNIQUE, user_id INTEGER NOT NULL REFERENCES users(id), public_key TEXT NOT NULL, platform VARCHAR(32) NOT NULL, app_version VARCHAR(32) NOT NULL, status VARCHAR(24) NOT NULL DEFAULT 'active', registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, last_activity_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS ix_authenticator_devices_user_id ON authenticator_devices(user_id);
CREATE INDEX IF NOT EXISTS ix_authenticator_devices_status ON authenticator_devices(status);
CREATE TABLE IF NOT EXISTS auth_challenges (id SERIAL PRIMARY KEY, challenge_id VARCHAR(64) NOT NULL UNIQUE, user_id INTEGER NOT NULL REFERENCES users(id), device_id INTEGER NOT NULL REFERENCES authenticator_devices(id), nonce VARCHAR(96) NOT NULL, number_hash VARCHAR(64) NOT NULL, application VARCHAR(120) NOT NULL DEFAULT 'XAI', request_context TEXT NOT NULL DEFAULT '{}', status VARCHAR(24) NOT NULL DEFAULT 'pending', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at TIMESTAMP NOT NULL, completed_at TIMESTAMP);
CREATE INDEX IF NOT EXISTS ix_auth_challenges_user_id ON auth_challenges(user_id); CREATE INDEX IF NOT EXISTS ix_auth_challenges_device_id ON auth_challenges(device_id); CREATE INDEX IF NOT EXISTS ix_auth_challenges_status ON auth_challenges(status);
CREATE TABLE IF NOT EXISTS auth_events (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), device_id INTEGER REFERENCES authenticator_devices(id), event_type VARCHAR(48) NOT NULL, result VARCHAR(24) NOT NULL, application VARCHAR(120) NOT NULL DEFAULT 'XAI', details TEXT NOT NULL DEFAULT '{}', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS ix_auth_events_user_id ON auth_events(user_id); CREATE INDEX IF NOT EXISTS ix_auth_events_device_id ON auth_events(device_id); CREATE INDEX IF NOT EXISTS ix_auth_events_event_type ON auth_events(event_type); CREATE INDEX IF NOT EXISTS ix_auth_events_created_at ON auth_events(created_at);
CREATE TABLE IF NOT EXISTS recovery_codes (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), code_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, used_at TIMESTAMP, CONSTRAINT uq_recovery_user_code UNIQUE(user_id,code_hash));
CREATE INDEX IF NOT EXISTS ix_recovery_codes_user_id ON recovery_codes(user_id);
CREATE TABLE IF NOT EXISTS auth_policies (id SERIAL PRIMARY KEY, scope VARCHAR(32) NOT NULL UNIQUE DEFAULT 'global', mfa_required BOOLEAN NOT NULL DEFAULT FALSE, totp_allowed BOOLEAN NOT NULL DEFAULT TRUE, push_allowed BOOLEAN NOT NULL DEFAULT FALSE, number_matching_required BOOLEAN NOT NULL DEFAULT TRUE, challenge_seconds INTEGER NOT NULL DEFAULT 120, session_minutes INTEGER NOT NULL DEFAULT 15);
