import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:provider/provider.dart';
import '../core/app_state.dart';

class AddAccountScreen extends StatefulWidget { const AddAccountScreen({super.key}); @override State<AddAccountScreen> createState()=>_AddAccountScreenState(); }
class _AddAccountScreenState extends State<AddAccountScreen> {
  final controller=TextEditingController(); bool scanning=false,busy=false; String? error;
  Future<void> add(String value) async { if(busy)return; setState(()=>busy=true); try { await context.read<AppState>().addFromUri(value); if(mounted)Navigator.pop(context); } on FormatException catch(e) { if(mounted)setState(()=>error=e.message); } catch(_) { if(mounted)setState(()=>error='Secure storage could not save this account.'); } finally { if(mounted)setState(()=>busy=false); } }
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Add account')),body:scanning?_scanner():ListView(padding:const EdgeInsets.all(24),children:[Text('Connect an authenticator',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:8),const Text('Scan the QR code shown by XAI or another standards-compatible service. TOTP codes work offline.'),const SizedBox(height:24),FilledButton.icon(onPressed:()=>setState(()=>scanning=true),icon:const Icon(Icons.qr_code_scanner),label:const Text('Scan QR code')),const SizedBox(height:24),const Divider(),const SizedBox(height:16),Text('Enter setup key manually',style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:8),const Text('Fallback for a setup key issued by a service. Do not invent a key.'),const SizedBox(height:12),TextField(controller:controller,autocorrect:false,enableSuggestions:false,decoration:const InputDecoration(labelText:'otpauth URI',hintText:'Paste the setup URI supplied by the service',border:OutlineInputBorder())),const SizedBox(height:12),OutlinedButton(onPressed:busy?null:()=>add(controller.text),child:const Text('Add standard TOTP account')),if(error!=null)Padding(padding:const EdgeInsets.only(top:16),child:Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error)))]));
  Widget _scanner()=>Stack(children:[MobileScanner(onDetect:(capture){final raw=capture.barcodes.firstOrNull?.rawValue;if(raw!=null){setState(()=>scanning=false);add(raw);}}),SafeArea(child:Padding(padding:const EdgeInsets.all(16),child:Align(alignment:Alignment.topLeft,child:FilledButton.tonalIcon(onPressed:()=>setState(()=>scanning=false),icon:const Icon(Icons.close),label:const Text('Cancel'))))),const Center(child:ExcludeSemantics(child:Icon(Icons.crop_free,size:240,color:Colors.white70)))]);
  @override void dispose(){controller.dispose();super.dispose();}
}
