import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:provider/provider.dart';

import '../core/app_state.dart';
import '../widgets/account_code_card.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  Future<void> _scan(BuildContext context) async {
    final value = await Navigator.of(context).push<String>(
      MaterialPageRoute(builder: (_) => const QrScannerScreen()),
    );
    if (value == null || !context.mounted) return;
    try {
      await context.read<AppState>().addFromUri(value);
    } catch (error) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('$error')));
      }
    }
  }

  Future<void> _manual(BuildContext context) async {
    final issuer = TextEditingController(text: 'XAI-Compress');
    final account = TextEditingController();
    final secret = TextEditingController();
    final state = context.read<AppState>();

    await showDialog<void>(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: const Text('Add account manually'),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextField(controller: issuer, decoration: const InputDecoration(labelText: 'Issuer')),
              TextField(controller: account, decoration: const InputDecoration(labelText: 'Account e-mail')),
              TextField(controller: secret, decoration: const InputDecoration(labelText: 'Base32 secret')),
            ],
          ),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(dialogContext), child: const Text('Cancel')),
          FilledButton(
            onPressed: () async {
              await state.addManual(
                issuer: issuer.text.trim(),
                accountName: account.text.trim(),
                secret: secret.text.trim(),
              );
              if (dialogContext.mounted) Navigator.pop(dialogContext);
            },
            child: const Text('Save'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final state = context.watch<AppState>();
    return Scaffold(
      appBar: AppBar(
        title: const Text('XAI Authenticator'),
        actions: [
          IconButton(onPressed: state.lock, icon: const Icon(Icons.lock_outline), tooltip: 'Lock'),
        ],
      ),
      body: state.accounts.isEmpty
          ? Center(
              child: Padding(
                padding: const EdgeInsets.all(24),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Icon(Icons.qr_code_2, size: 96),
                    const SizedBox(height: 20),
                    Text('No accounts enrolled', style: Theme.of(context).textTheme.headlineSmall),
                    const SizedBox(height: 8),
                    const Text('Scan the QR code generated by the XAI-Compress backend.'),
                  ],
                ),
              ),
            )
          : ListView.separated(
              padding: const EdgeInsets.all(16),
              itemCount: state.accounts.length,
              separatorBuilder: (_, __) => const SizedBox(height: 12),
              itemBuilder: (context, index) => AccountCodeCard(account: state.accounts[index]),
            ),
      floatingActionButton: PopupMenuButton<String>(
        onSelected: (value) => value == 'scan' ? _scan(context) : _manual(context),
        itemBuilder: (_) => const [
          PopupMenuItem(value: 'scan', child: ListTile(leading: Icon(Icons.qr_code_scanner), title: Text('Scan QR code'))),
          PopupMenuItem(value: 'manual', child: ListTile(leading: Icon(Icons.keyboard), title: Text('Enter secret'))),
        ],
        child: const FloatingActionButton.extended(
          onPressed: null,
          icon: Icon(Icons.add),
          label: Text('Add account'),
        ),
      ),
    );
  }
}

class QrScannerScreen extends StatefulWidget {
  const QrScannerScreen({super.key});
  @override
  State<QrScannerScreen> createState() => _QrScannerScreenState();
}

class _QrScannerScreenState extends State<QrScannerScreen> {
  bool handled = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Scan enrollment QR')),
      body: MobileScanner(
        onDetect: (capture) {
          if (handled) return;
          final value = capture.barcodes.firstOrNull?.rawValue;
          if (value == null || !value.startsWith('otpauth://totp/')) return;
          handled = true;
          Navigator.pop(context, value);
        },
      ),
    );
  }
}
